### ISSUE TITLE
Changeing colors

### ISSUE THREAD

**Issue by DanielRios549** [mcder3/Nilium-Plasma-Theme#1]
I discover this theme today and I really love it, it is the best I've ever found, but I use KDE Plasma on Linux Mint, and I would like a green version, maybe something like "Nilium-blue", "Nilium-green", for exemple. If this won't be possible, can you share links from where I can learn how to create and modify these themes?

**Comment by mcder3** [comment]
The only drawback that I see when creating theme of different colors is the difficulty of maintaining them, that's why I tried to keep the theme in one color.

unfortunately there is no guide to create themes for plasma... the knowledge that I have acquired has been thanks to design themes from KDE 4.3 by means of inverse engineering in the base theme (Oxygen, Air and Breeze)

**Comment by DanielRios549** [comment]
I understand man, I was learning how to modify theme by changing the themes too, I modified Nilium a little, but I think it is not good enough for share with others. Maybe this really is the best option to learn.
